name: Release

on:
  release:
    types:
      - published

jobs:
  call-workflow:
    uses: radiorabe/actions/.github/workflows/release-ansible-collection.yaml@6373540d4ab86c4ce044b6a67e96aecddf22c7c9 # v0.45.1
    secrets:
      GALAXY_API_KEY: ${{ secrets.GALAXY_API_KEY }}
