name: Lint and Test

on:
  pull_request:
    branches:
      - main

jobs:
  call-workflow:
    uses: radiorabe/actions/.github/workflows/test-ansible-collection.yaml@b37e51397726092d8462a2a9b676ea5a5e3a8deb # v0.44.1
  github-actions:
    permissions:
      contents: read
      security-events: write # so zizmor can publish results to the Security tab
    uses: radiorabe/actions/.github/workflows/test-github-actions.yaml@b37e51397726092d8462a2a9b676ea5a5e3a8deb # v0.44.1

  molecule:
    name: Molecule Test - ${{ matrix.scenario }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        scenario:
          - default

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Molecule test
        run: |
          cd roles/user_namespace
          molecule test -s ${{ matrix.scenario }}
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          ANSIBLE_ALLOW_BROKEN_CONDITIONALS: 'True'
